### ISSUE TITLE
Is CUDA 11.6 supported?

### ISSUE THREAD

**Issue by hasnainv** [megvii-research/CREStereo#2]
This is a really promising project, congratulations and thanks for releasing it!

I'm trying to run the test script with your Eth3d model and this command:
`python3 test.py --model_path path_to_mge_model --left img/test/left.png --right img/test/right.png --size 1024x1536 --output disparity.png`

But the code hangs up and doesn't return from this line in extractor.py:82:
`self.conv2 = M.Conv2d(128, output_dim, kernel_size=1)`

which is called form `load_model` in test.py:15
`model = Model(max_disp=256, mixed_precision=False, test_mode=True)`

My GPU is NVIDIA RTX A6000 and the CUDA version on the system is v11.6

**Comment by jucic** [comment]
same problem with you, have you sloved it?

**Comment by hasnainv** [comment]
Nope, I haven't been able to solve it. Have you tried running it with CUDA 10? 
I wonder if it is a GPU issue or a CUDA issue

**Comment by DY-ATL** [comment]
https://www.megengine.org.cn/doc/stable/en/user-guide/install/index.html#cuda
This may help.

**Comment by luhu65** [comment]
whether you have loaded pre-trained model？

**Comment by Yizhou-Li-CV** [comment]
@hasnainv For my case, my Cuda version is 11.4 and I install the MegEngine using the default command "pip3 install megengine -f https://megengine.org.cn/whl/mge.html". But this command will install the compiled version based on Cuda 10.1, which doesn't match the Cuda version of my PC. And I meet the same issue as you where the test code hangs up.

After this I tried to install the unofficial compiled version based on Cuda 11 (see https://github.com/Qsingle/MegEngine_CU11), and the test code works. Hope this can help.

**Comment by jucic** [comment]
I failed with cuda 11.3 and then successed with cuda 10.2

**Comment by ibaiGorordo** [comment]
I have not tried training, but I was able to run with CUDA 11.3 in my Pytorch implementation, in case someone needs it:
https://github.com/ibaiGorordo/CREStereo-Pytorch

**Comment by WeijieChen99** [comment]
> @hasnainv For my case, my CUDA version is 11.4 and I installed the MegEngine using the default command "pip3 install megengine -f https://megengine.org.cn/whl/mge.html". But this command will install the precompiled version based on CUDA 10.1, which didn't match the CUDA version of my PC. And I met the same issue as you where the test code hung up.
> 
> After this I tried to install the unofficial precompiled version based on CUDA 11 (see https://github.com/Qsingle/MegEngine_CU11), and the test code works. Hope this can help.

Hello, I installed the unofficial precompiled version based on CUDA 11, but in my case, I faced the following question:
[`08 20:48:14[mgb] ERR async cuda init failed: assertion `CUDNN_VERSION == cudnnGetVersion()' failed at ../../../../../../dnn/src/cuda/handle.cpp:58: megdnn::cuda::HandleImpl::HandleImpl(megcoreComputingHandle_t)
extra message: cudnn version mismatch: compiled with 8101; detected 8201 at runtime, may caused by customized environment, for example LD_LIBRARY_PATH on LINUX and PATH on Windows!!`]
Have you met before?And how to solve this problem?
My GPU is RTX 3080Ti, and the CUDA version on the system is 11.2 , and CUDNN vesion is 8.1.1

**Comment by WeijieChen99** [comment]
> @hasnainv For my case, my CUDA version is 11.4 and I installed the MegEngine using the default command "pip3 install megengine -f https://megengine.org.cn/whl/mge.html". But this command will install the precompiled version based on CUDA 10.1, which didn't match the CUDA version of my PC. And I met the same issue as you where the test code hung up.
> 
> After this I tried to install the unofficial precompiled version based on CUDA 11 (see https://github.com/Qsingle/MegEngine_CU11), and the test code works. Hope this can help.

Hello, I installed the unofficial precompiled version based on CUDA 11, but in my case, I faced the following question:
`08 20:48:14[mgb] ERR async cuda init failed: assertion `CUDNN_VERSION == cudnnGetVersion()' failed at ../../../../../../dnn/src/cuda/handle.cpp:58: megdnn::cuda::HandleImpl::HandleImpl(megcoreComputingHandle_t)
extra message: cudnn version mismatch: compiled with 8101; detected 8201 at runtime, may caused by customized environment, for example LD_LIBRARY_PATH on LINUX and PATH on Windows!!`
`RuntimeError: assertion `CUDNN_VERSION == cudnnGetVersion()' failed at ../../../../../../dnn/src/cuda/handle.cpp:58: megdnn::cuda::HandleImpl::HandleImpl(megcoreComputingHandle_t)
extra message: cudnn version mismatch: compiled with 8101; detected 8201 at runtime, may caused by customized environment, for example LD_LIBRARY_PATH on LINUX and PATH on Windows!!`
Have you met before?And how to solve this problem?
My GPU is RTX 3080Ti, and the CUDA version on the system is 11.2 , and CUDNN version is 8.1.1.

**Comment by WeijieChen99** [comment]
> @hasnainv For my case, my CUDA version is 11.4 and I installed the MegEngine using the default command "pip3 install megengine -f https://megengine.org.cn/whl/mge.html". But this command will install the precompiled version based on CUDA 10.1, which didn't match the CUDA version of my PC. And I met the same issue as you where the test code hung up.
> 
> After this I tried to install the unofficial precompiled version based on CUDA 11 (see https://github.com/Qsingle/MegEngine_CU11), and the test code works. Hope this can help.

Hello, I installed the unofficial precompiled version based on CUDA 11, but in my case, I faced the following question:
`08 20:48:14[mgb] ERR async cuda init failed: assertion `CUDNN_VERSION == cudnnGetVersion()' failed at ../../../../../../dnn/src/cuda/handle.cpp:58: megdnn::cuda::HandleImpl::HandleImpl(megcoreComputingHandle_t)
extra message: cudnn version mismatch: compiled with 8101; detected 8201 at runtime, may caused by customized environment, for example LD_LIBRARY_PATH on LINUX and PATH on Windows!!
`
`RuntimeError: assertion `CUDNN_VERSION == cudnnGetVersion()' failed at ../../../../../../dnn/src/cuda/handle.cpp:58: megdnn::cuda::HandleImpl::HandleImpl(megcoreComputingHandle_t)
extra message: cudnn version mismatch: compiled with 8101; detected 8201 at runtime, may caused by customized environment, for example LD_LIBRARY_PATH on LINUX and PATH on Windows!!
`
Have you met before? And how to solve this problem?
My GPU is RTX 3080Ti, and the CUDA version on the system is 11.2 , and CUDNN version is 8.1.1.

**Comment by WeijieChen99** [comment]
> @hasnainv For my case, my CUDA version is 11.4 and I installed the MegEngine using the default command "pip3 install megengine -f https://megengine.org.cn/whl/mge.html". But this command will install the precompiled version based on CUDA 10.1, which didn't match the CUDA version of my PC. And I met the same issue as you where the test code hung up.
> 
> After this I tried to install the unofficial precompiled version based on CUDA 11 (see https://github.com/Qsingle/MegEngine_CU11), and the test code works. Hope this can help.



> @hasnainv For my case, my CUDA version is 11.4 and I installed the MegEngine using the default command "pip3 install megengine -f https://megengine.org.cn/whl/mge.html". But this command will install the precompiled version based on CUDA 10.1, which didn't match the CUDA version of my PC. And I met the same issue as you where the test code hung up.
> 
> After this I tried to install the unofficial precompiled version based on CUDA 11 (see https://github.com/Qsingle/MegEngine_CU11), and the test code works. Hope this can help.

Hello! I have installed the unofficial precompiled version based on CUDA 11, but for my case, I faced the following question:
`08 20:48:14[mgb] ERR async cuda init failed: assertion `CUDNN_VERSION == cudnnGetVersion()' failed at ../../../../../../dnn/src/cuda/handle.cpp:58: megdnn::cuda::HandleImpl::HandleImpl(megcoreComputingHandle_t)
extra message: cudnn version mismatch: compiled with 8101; detected 8201 at runtime, may caused by customized environment, for example LD_LIBRARY_PATH on LINUX and PATH on Windows!!
`  

`RuntimeError: assertion `CUDNN_VERSION == cudnnGetVersion()' failed at ../../../../../../dnn/src/cuda/handle.cpp:58: megdnn::cuda::HandleImpl::HandleImpl(megcoreComputingHandle_t)
extra message: cudnn version mismatch: compiled with 8101; detected 8201 at runtime, may caused by customized environment, for example LD_LIBRARY_PATH on LINUX and PATH on Windows!!`

Have you met before?

**Comment by WeijieChen99** [comment]
> @hasnainv For my case, my CUDA version is 11.4 and I installed the MegEngine using the default command "pip3 install megengine -f https://megengine.org.cn/whl/mge.html". But this command will install the precompiled version based on CUDA 10.1, which didn't match the CUDA version of my PC. And I met the same issue as you where the test code hung up.
> 
> After this I tried to install the unofficial precompiled version based on CUDA 11 (see https://github.com/Qsingle/MegEngine_CU11), and the test code works. Hope this can help.

Hello! I have installed the unofficial precompiled version based on CUDA 11, but for my case, I faced the following question:
![捕获8](https://user-images.githubusercontent.com/84511586/162567387-2d88ded1-74fa-4307-9ae3-25b96e194992.PNG)
Have you met before?

**Comment by WeijieChen99** [comment]
> @hasnainv For my case, my CUDA version is 11.4 and I installed the MegEngine using the default command "pip3 install megengine -f https://megengine.org.cn/whl/mge.html". But this command will install the precompiled version based on CUDA 10.1, which didn't match the CUDA version of my PC. And I met the same issue as you where the test code hung up.
> 
> After this I tried to install the unofficial precompiled version based on CUDA 11 (see https://github.com/Qsingle/MegEngine_CU11), and the test code works. Hope this can help.

Hello! I have installed the unofficial precompiled version based on CUDA 11, but for my case, I faced the following question:

![捕获8](https://user-images.githubusercontent.com/84511586/162567468-419e30b0-7765-451d-9db8-822b8a85a249.PNG)

Have you met before? And how to solve this problem? My GPU is RTX 3080Ti and my CUDA version in my system is 11.2 and the CUDNN version is 8.1.1.

**Comment by Yizhou-Li-CV** [comment]
Hi @WeijieChen99, I haven't met this issue before. It looks like the CUDNN version been used now is not 8.2.1 rather than 8.1.1. You may try to install the CUDNN again like `conda install cudnn=8.1.1`

**Comment by WeijieChen99** [comment]
> Hi @WeijieChen99, I haven't met this issue before. It looks like the CUDNN version been used now is 8.2.1 rather than 8.1.1. You may try to reinstall the CUDNN using command like `conda install cudnn=8.1.1`.

Thanks, I have used command `conda install -c esri cudnn` which is recommended by https://anaconda.org/, what is your version? I just used command `pip install MegEngine-1.8.2+cu112-cp38-cp38-manylinux2014_x86_64.whl` and `conda install cudatoolkit=11.2` and `conda install cudnn=8.1.1`

**Comment by WeijieChen99** [comment]
> Hi @WeijieChen99, I haven't met this issue before. It looks like the CUDNN version been used now is 8.2.1 rather than 8.1.1. You may try to reinstall the CUDNN using command like `conda install cudnn=8.1.1`.

Thanks, I have used command `conda install -c esri cudnn` which is recommended by https://anaconda.org/, what is your version? After downloading the precompiled version. I just used 4 commands `python3 -m pip install -r requirements.txt` and `pip install MegEngine-1.8.2+cu112-cp38-cp38-manylinux2014_x86_64.whl` and `conda install cudatoolkit=11.2` and `conda install -c esri cudnn` , was I right?

**Comment by hasnainv** [comment]
Excellent, thank you @ibaiGorordo, I'll test it out right away

**Comment by Yizhou-Li-CV** [comment]
@WeijieChen99 Sorry I am not pretty sure but I think you may not do `python3 -m pip install -r requirements.txt` as MegEngine is included in the _requirements.txt_, which will cause the installation of MegEngine with CUDA10. I am not sure if this will cause any trouble. 

You may delete the _MegEngine_ from _requirements.txt_ first, and `python3 -m pip install -r requirements.txt`, and then `pip install MegEngine-1.8.2+cu112-cp38-cp38-manylinux2014_x86_64.whl`. It there is still error about CUDNN version, you may try to reinstall the CUDNN of certain version like `conda install cudnn=8.1.1`.

**Comment by WeijieChen99** [comment]
> 

Thanks a lot! I'll try it right away.

**Comment by WeijieChen99** [comment]
@Yizhou-Li-CV Thanks a lot! I'll try it right away.

**Comment by Qjizhi** [comment]
based on @ibaiGorordo's code, I enabled the training process with pytorch, here it is https://github.com/Qjizhi/CREStereo-Pytorch, thanks both @ibaiGorordo  and the authors of this paper.

**Comment by Refraggerator** [comment]
> based on @ibaiGorordo's code, I enabled the training process with pytorch, here it is https://github.com/Qjizhi/CREStereo-Pytorch, thanks both @ibaiGorordo and the authors of this paper.

Hey,

I trained an own model with your repository..
But when I want to test the model i get the following errors:

![image](https://user-images.githubusercontent.com/59026629/219065389-cdf3c386-36f6-4281-a2b6-60731b88577b.png)


How do i have to use the own trained model?
I am currently just using the /train_log/models/epoch-XXX.pth file to start the test_model.py
Are there any more steps i have to do so i can use my own trained model?

Thanks in advance :)

**Comment by Refraggerator** [comment]
> > based on @ibaiGorordo's code, I enabled the training process with pytorch, here it is https://github.com/Qjizhi/CREStereo-Pytorch, thanks both @ibaiGorordo and the authors of this paper.
> 
> Hey,
> 
> I trained an own model with your repository.. But when I want to test the model i get the following errors:
> 
> ![image](https://user-images.githubusercontent.com/59026629/219065389-cdf3c386-36f6-4281-a2b6-60731b88577b.png)
> 
> How do i have to use the own trained model? I am currently just using the /train_log/models/epoch-XXX.pth file to start the test_model.py Are there any more steps i have to do so i can use my own trained model?
> 
> Thanks in advance :)

Ok i just set the "strict" = False in "model.load_state_dict(torch.load(model_path), strict=False)" and it seems to work.
What does this do? Will it affect the results, or is this just for loading the Model in another format?

**Comment by Qjizhi** [comment]
> > based on @ibaiGorordo's code, I enabled the training process with pytorch, here it is https://github.com/Qjizhi/CREStereo-Pytorch, thanks both @ibaiGorordo and the authors of this paper.
> 
> Hey,
> 
> I trained an own model with your repository.. But when I want to test the model i get the following errors:
> 
> ![image](https://user-images.githubusercontent.com/59026629/219065389-cdf3c386-36f6-4281-a2b6-60731b88577b.png)
> 
> How do i have to use the own trained model? I am currently just using the /train_log/models/epoch-XXX.pth file to start the test_model.py Are there any more steps i have to do so i can use my own trained model?
> 
> Thanks in advance :)

@FisterOfYourSister  try this one
```python
if 'state_dict' in pretrained_dict.keys():
    model.load_state_dict(pretrained_dict["state_dict"], strict=True)
else:
    model.load_state_dict(pretrained_dict, strict=True)
```

**Comment by Qjizhi** [comment]
> > based on @ibaiGorordo's code, I enabled the training process with pytorch, here it is https://github.com/Qjizhi/CREStereo-Pytorch, thanks both @ibaiGorordo and the authors of this paper.
> 
> Hey,
> 
> I trained an own model with your repository.. But when I want to test the model i get the following errors:
> 
> ![image](https://user-images.githubusercontent.com/59026629/219065389-cdf3c386-36f6-4281-a2b6-60731b88577b.png)
> 
> How do i have to use the own trained model? I am currently just using the /train_log/models/epoch-XXX.pth file to start the test_model.py Are there any more steps i have to do so i can use my own trained model?
> 
> Thanks in advance :)

@FisterOfYourSister btw, I also enabled the DDP training, which will be much faster, feel free to try.

**Comment by Refraggerator** [comment]
> > > based on @ibaiGorordo's code, I enabled the training process with pytorch, here it is https://github.com/Qjizhi/CREStereo-Pytorch, thanks both @ibaiGorordo and the authors of this paper.
> > 
> > 
> > Hey,
> > I trained an own model with your repository.. But when I want to test the model i get the following errors:
> > ![image](https://user-images.githubusercontent.com/59026629/219065389-cdf3c386-36f6-4281-a2b6-60731b88577b.png)
> > How do i have to use the own trained model? I am currently just using the /train_log/models/epoch-XXX.pth file to start the test_model.py Are there any more steps i have to do so i can use my own trained model?
> > Thanks in advance :)
> 
> @FisterOfYourSister try this one
> 
> ```python
> if 'state_dict' in pretrained_dict.keys():
>     model.load_state_dict(pretrained_dict["state_dict"], strict=True)
> else:
>     model.load_state_dict(pretrained_dict, strict=True)
> ```

Ok, but where do i get the pretrained_dict from? I dont really get, where this code snippet goes..

And i already tried DDP Training. How much faster should it approximately be?
Im currently running on a RTX4070ti and my Batchsize_single is 2.
There is basically no difference between DDP on and off.

**Comment by Qjizhi** [comment]
> 

@Refraggerator You can simply use this code
```python
device = torch.device('cpu')
pretrained_dict = torch.load(model_path, map_location=device)
```
and the model could be converted with this code https://github.com/Qjizhi/CREStereo-Pytorch/blob/main/convert_weights.py

For DDP, it depends on how many GPUs you have, if you have one, the training time won't be much different.
